name: dependency_manager
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  manabie_pdf_annotations:
    # path: ../../flutter_manabie_packages/packages/manabie_pdf_annotations/
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_pdf_annotations
      ref: manabie_pdf_annotations_0.0.11

  flutter_localizations:
    sdk: flutter

  # Redux
  redux: ^4.0.0
  flutter_redux: ^0.6.0
  redux_logging: ^0.4.0
  equatable: ^1.0.1
  connectivity: ^0.4.9
  connectivity_for_web: ^0.3.1
  shared_preferences: 0.5.6
  tiengviet: ^0.3.0

  # Firebase & Google
  firebase_messaging: ^6.0.13
  firebase_crashlytics: ^0.1.2+3
  firebase_remote_config: ^0.3.0+1

  email_validator: ^1.0.3

  image_picker: ^0.6.2+3
  country_pickers: ^1.2.0
  intl: any
  ntp: ^1.0.5
  built_value: ^7.1.0
  built_collection: ^4.3.2
  responsive_builder: ^0.3.0
  url_launcher: ^5.4.7
  camera: ^0.5.8+2
  date_range_picker:
    # path: ../../date_range_picker
    git:
      url: git@github.com:manabie-com/date_range_picker.git


  # DI
  inject:
    git:
      url: git@github.com:google/inject.dart.git
      path: package/inject

  # Manabie
  manabie_custom_load_more:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_custom_load_more

  manabie_navigation:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_navigation
      ref: manabie_navigation_1.0.0

  manabie_messaging:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_messaging
      ref: manabie_messaging_1.3.5
  #
  manabie_subject:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_subject

  manabie_assigment:
    # path: ../../flutter_manabie_packages/packages/manabie_assigment
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_assigment
      ref: manabie_assignment_1.1.47

  manabie_topic:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_topic
      ref: manabie_topic_1.2.0

  manabie_quiz:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_quiz
      ref: manabie_quiz_1.3.2

  manabie_statistic:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_statistic
      ref: manabie_statistic_1.2.1

  manabie_lo:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_lo
      ref: manabie_lo_1.2.11

  manabie_chapter:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_chapter
      ref: manabie_chapter_1.2.4

  manabie_course:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_course
      ref: manabie_course_1.2.13

  manabie_lesson:
    #    path: ../../flutter_manabie_packages/packages/manabie_lesson
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_lesson
      ref: manabie_lesson_1.0.4

  manabie_notification:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_notification
      ref: manabie_notification_1.1.0

  manabie_user:
    #     path: ../../flutter_manabie_packages/packages/manabie_user
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_user
      ref: manabie_user_1.0.14

  manabie_datetime_utils:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_datetime_utils

  manabie_class:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_class
      ref: manabie_class_1.0.8

  manabie_remote_config:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_remote_config
      ref: manabie_remote_config_1.0.1

  manabie_debug:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_debug

  manabie_brightcove:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_brightcove
      ref: manabie_brightcove_1.0.20

  manabie_school:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_school
      ref: manabie_school_1.0.1

  manabie_agora:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_agora
      ref: manabie_agora_1.1.12

  manabie_white_board:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_white_board
      ref: manabie_white_board_1.0.9

  jprep_ui:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: jprep_packages/jprep_ui
      ref: jprep_ui_0.0.41

  manabie_study_plan:
    #    path: ../../flutter_manabie_packages/packages/manabie_study_plan
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_study_plan
      ref: manabie_study_plan_1.0.3

  manabie_todo:
    #    path: ../../flutter_manabie_packages/packages/manabie_todo
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_todo
      ref: manabie_todo_1.0.10

  scrollable_positioned_list: ^0.1.8
  visibility_detector: ^0.1.5

  #  cached_network_image: ^2.0.0-rc.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  share: ^0.6.3+5
  launch_review: ^2.0.0

  #logging
  logging: ^0.11.3+2
  package_info: ^0.4.0+13
  pin_input_text_field: ^3.0.1

dev_dependencies:
  platform: 3.0.0-nullsafety.1
  flutter_test:
    sdk: flutter
  build_runner: any
  built_value_generator: ^7.1.0

  postgres: ^2.1.1
  inject_generator:
    git:
      url: git@github.com:google/inject.dart.git
      path: package/inject_generator
      ref: 7c3cbf6
  reflectable: ^2.2.4
  mockito: ^4.1.1
  flutter_launcher_icons: ^0.7.4
  intl_translation: ^0.17.8
  pedantic: ^1.9.0
  flutter_datetime_picker: 1.2.5

  # Test
  test: any
  manabie_bdd:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_bdd

  grpc:
    git:
      url: git@github.com:phamnhuvu-dev/grpc-dart.git
      ref: update-2.8.0

dependency_overrides:
  intl: 0.17.0-nullsafety.2
  core_ui:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/technical/core_ui
      ref: core_ui_0.1.2

  audioplayers: ^0.16.1
  webview_flutter: ^1.0.0
  platform: 3.0.0-nullsafety.1
  dart_style: 1.3.6
  websafe_svg: ^1.1.4
  http: ^0.12.2
  toast: ^0.1.5
  cached_network_image: 2.3.3
  flutter_cache_manager: ^2.0.0
  redux_epics: ^0.14.0
  extended_image: 1.3.1-dev
  file: ^5.2.1

  date_range_picker:
    git:
      url: git@github.com:manabie-com/date_range_picker.git

  manabie_file:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_file
      ref: implement-upload-large-file

  manabie_core:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_core
      ref: manabie_core_1.0.25

  manabie_grpc:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_grpc
      ref: manabie_grpc_1.2.32

  manabie_token:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_token
      ref: manabie_token_0.0.1
  app_settings: ^4.0.2

  flutter_image_compress: 0.7.0
  grpc:
    git:
      url: git@github.com:phamnhuvu-dev/grpc-dart.git
      ref: update-2.8.0

  flutter_svg: ^0.19.0
  reflectable: ^2.2.4
  flutter_screenutil: ^3.2.0

  bob_dart_client:
    git:
      url: git@github.com:manabie-com/bob_dart_client.git
      ref: develop

  tom_dart_client:
    git:
      url: git@github.com:manabie-com/tom_dart_client.git

  manabie_ui:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_ui
      ref: manabie_ui_1.0.106

  manabie_math_jax:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_math_jax
      ref: manabie_math_jax_1.2.7

  manabie_utils:
    git:
      url: git@github.com:manabie-com/flutter_manabie_packages.git
      path: packages/manabie_utils
      ref: manabie_utils_1.0.1

  manabuf_dart:
    git:
      url: git@github.com:manabie-com/manabuf-dart.git
      ref: develop

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
